 steps:
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: python
      entrypoint: python
      args: ['-m', 'pip', 'install', 'build', 'pytest', 'lxml','bs4','langchain','openai','tiktoken','fastapi uvicorn[standard]', '--user'] 
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'build']         

artifacts:
       pythonPackages:
       - repository: 'https://europe-west3-docker.pkg.dev/langchain-docs-396117/summary-app-2'
          paths: ['dist/*']             